[tool.vulture]
make_whitelist = true
paths = ["."]
exclude = ["/tests", "types.py", "conftest.py"]
sort_by_size = true
min_confidence = 60
ignore_names = [
  "email_body",
  "email_subject",
  "encoding",
  "field_names",
  "is_health_check",
  "lambda_context",
  "lambda_handler",
  "metadata",
  "recipient_email_address",
  "recipient_id",
]
