# For documentation see here - https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml
service: dos-integration
frameworkVersion: '2'

configValidationMode: error

provider:
  name: aws
  lambdaHashingVersion: 20201221
  architecture: x86_64
  region: ${env:AWS_REGION}
  deploymentBucket:
    blockPublicAccess: true
    skipPolicySetup: true
  tags:
    Environment: ${env:ENVIRONMENT}
    PROFILE: ${env:PROFILE}
    Product: ${env:PROJECT_GROUP_SHORT}
    Programme: ${env:PROGRAMME}
    Service: ${env:PROJECT_GROUP_SHORT}
  # iam:
  #   role:
  #     name: dos-integration-${sls:stage}-lambda-role
  #     statements:
        # - Effect: 'Allow'
        #   Resource: 'TODO'
        #   Action: 'TODO' #This need to be restricted when used
        # - Effect: 'Deny'
        #   Resource: 'TODO'
        #   Action: 'TODO'

plugins:
  - serverless-localstack
  - serverless-vpc-discovery

custom:
  localstack:
    # Documentation - https://github.com/localstack/serverless-localstack
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    docker:
      sudo: False
  # vpcDiscovery:
  #   # Documentation - https://www.serverless.com/plugins/serverless-vpc-discovery
  #   vpcName: '${env:AWS_VPC_NAME}'
  #   subnets:
  #     - tagKey: Name
  #       tagValues:
  #         - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}a'
  #         - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}b'
  #         - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}c'
  #   securityGroups:
  #     - tagKey: Name
  #       tagValues:
  #         - 'uec-pu-apu-2429-rds'

functions:
  event-sender:
    image: ${env:AWS_SAME_ACCOUNT_DOCKER_REGISTRY}/event-sender:latest
    architecture: x86_64
    name: ${env:PROJECT_ID}-${sls:stage}-event-sender
    description: ${sls:stage} Event Sender lambda
    memorySize: 512
    timeout: 10
    tags:
      PYTHON_VERSION: ${env:APP_PYTHON_VERSION}
    environment:
      PROFILE: ${env:PROFILE}
    # tracing:
    #   lambda: true

#resources:
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
