# For documentation see here - https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml
service: ${env:TEAM_ID}
frameworkVersion: '2'

configValidationMode: error
unresolvedVariablesNotificationMode: error

provider:
  name: aws
  lambdaHashingVersion: 20201221
  architecture: x86_64
  region: ${env:AWS_REGION}
  deploymentBucket:
    blockPublicAccess: true
    skipPolicySetup: true
  tags:
    Environment: ${env:ENVIRONMENT}
    PROFILE: ${env:PROFILE}
    Product: ${env:PROJECT_GROUP_SHORT}
    Programme: ${env:PROGRAMME}
    Service: ${env:PROJECT_GROUP_SHORT}

plugins:
  - serverless-vpc-discovery
  - serverless-localstack
custom:
  vpcDiscovery:
    # Documentation - https://www.serverless.com/plugins/serverless-vpc-discovery
    vpcName: '${env:AWS_VPC_NAME}'
    subnets:
      - tagKey: Name
        tagValues:
          - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}a'
          - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}b'
          - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}c'
    securityGroups:
      - tagKey: Name
        tagValues:
          - '${env:TF_VAR_lambda_security_group_name}'

functions:
  event-sender:
    image: ${env:AWS_SAME_ACCOUNT_DOCKER_REGISTRY}/event-sender:${env:VERSION}
    architecture: x86_64
    name: ${env:PROJECT_ID}-${sls:stage}-event-sender
    description: ${sls:stage} Event Sender lambda
    memorySize: 512
    timeout: 60
    tags:
      PYTHON_VERSION: ${env:PYTHON_VERSION}
    environment:
      PROFILE: ${env:PROFILE}
      POWERTOOLS_SERVICE_NAME: ${env:TEAM_ID}
      POWERTOOLS_TRACER_CAPTURE_RESPONSE: true
      POWERTOOLS_TRACER_CAPTURE_ERROR: true
      POWERTOOLS_TRACE_MIDDLEWARES: true
      LOG_LEVEL: ${env:LOG_LEVEL}
      DOS_API_GATEWAY_USERNAME: ${env:DOS_API_GATEWAY_USERNAME}
      DOS_API_GATEWAY_PASSWORD: ${env:DOS_API_GATEWAY_PASSWORD}
      DOS_API_GATEWAY_REQUEST_TIMEOUT: ${env:DOS_API_GATEWAY_REQUEST_TIMEOUT}
      DOS_API_GATEWAY_URL: ${env:DOS_API_GATEWAY_URL}
    tracing: Active

#resources:
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
