# For documentation see here - https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml
service: uec-dos-integration
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  deploymentMethod: direct
  lambdaHashingVersion: 20201221
  architecture: x86_64
  region: ${env:AWS_REGION}
  versionFunctions: false
  deploymentBucket:
    blockPublicAccess: true
    skipPolicySetup: true
  stackTags:
    Environment: ${env:ENVIRONMENT}
    PROFILE: ${env:PROFILE}
    Product: ${env:PROJECT_ID}
    Programme: ${env:PROGRAMME}
    Service: ${env:PROJECT_ID}
  tags:
    Environment: ${env:ENVIRONMENT}
    PROFILE: ${env:PROFILE}
    Product: ${env:PROJECT_ID}
    Programme: ${env:PROGRAMME}
    Service: ${env:PROJECT_ID}
  environment:
    PROFILE: ${env:PROFILE}
    ENV: ${env:ENVIRONMENT}
    POWERTOOLS_SERVICE_NAME: ${env:PROGRAMME}-${env:TEAM_ID}-${sls:stage}
    POWERTOOLS_TRACER_CAPTURE_RESPONSE: true
    POWERTOOLS_TRACER_CAPTURE_ERROR: true
    POWERTOOLS_TRACE_MIDDLEWARES: true
    LOG_LEVEL: ${env:LOG_LEVEL}
    BUILD_TIMESTAMP: ${env:VERSION}
    IMAGE_VERSION: ${env:VERSION}
  logs:
    restApi:
      format: '{"requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod","path":"$context.path","resourcePath":"$context.resourcePath","status":"$context.status","responseLatency":"$context.responseLatency","xrayTraceId":"$context.xrayTraceId","integrationRequestId":"$context.integration.requestId","functionResponseStatus":"$context.integration.status","integrationLatency":"$context.integration.latency","integrationServiceStatus":"$context.integration.integrationStatus","ip":"$context.identity.sourceIp","userAgent":"$context.identity.userAgent"}'
  tracing:
    lambda: true
    apiGateway: true
  endpointType: regional

plugins:
  - serverless-vpc-discovery

functions:

  change-event-dlq-handler:
    image: ${env:DOCKER_REGISTRY}/change-event-dlq-handler:${env:VERSION}
    architecture: x86_64
    name: ${env:PROJECT_ID}-${sls:stage}-change-event-dlq-handler
    description: ${sls:stage} Change Event DLQ Handler lambda
    memorySize: 128
    timeout: 30
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/${env:TF_VAR_change_event_dlq_handler_role_name}
    environment:
      CHANGE_EVENTS_TABLE_NAME: ${env:TF_VAR_change_events_table_name}
    maximumRetryAttempts: 0

  dos-db-update-dlq-handler:
    image: ${env:DOCKER_REGISTRY}/dos-db-update-dlq-handler:${env:VERSION}
    architecture: x86_64
    name: ${env:PROJECT_ID}-${sls:stage}-dos-db-update-dlq-handler
    description: ${sls:stage} DoS DB Update DLQ Handler lambda
    memorySize: 128
    timeout: 30
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/${env:TF_VAR_dos_db_update_dlq_handler_role_name}
    maximumRetryAttempts: 0

  event-replay:
    image: ${env:DOCKER_REGISTRY}/event-replay:${env:VERSION}
    architecture: x86_64
    name: ${env:PROJECT_ID}-${sls:stage}-event-replay
    description: ${sls:stage} Event Replay lambda
    memorySize: 128
    timeout: 30
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/${env:TF_VAR_event_replay_role_name}
    environment:
      CHANGE_EVENTS_TABLE_NAME: ${env:TF_VAR_change_events_table_name}
      CHANGE_EVENT_SQS_NAME: ${env:TF_VAR_change_event_queue_name}
    maximumRetryAttempts: 0

  orchestrator:
    image: ${env:DOCKER_REGISTRY}/orchestrator:${env:VERSION}
    architecture: x86_64
    name: ${env:PROJECT_ID}-${sls:stage}-orchestrator
    description: ${sls:stage} Orchestrator
    memorySize: 128
    timeout: 295 # 4 minutes and 55 seconds (should mean max 5 second gap every 5 mins)
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/${env:TF_VAR_orchestrator_role_name}
    maximumRetryAttempts: 0
    reservedConcurrency: 1 # ensure only one orchestrator running at a time
    events:
      - schedule: rate(1 minute)
    environment:
      CHANGE_EVENTS_TABLE_NAME: ${env:TF_VAR_change_events_table_name}
      CIRCUIT: DOS_API_GATEWAY
      UPDATE_REQUEST_QUEUE_URL: ${env:update_request_queue_url}
      DOS_TRANSACTIONS_PER_SECOND: ${env:DOS_TRANSACTIONS_PER_SECOND}
      EVENT_SENDER_FUNCTION_NAME: ${env:PROJECT_ID}-${sls:stage}-service-sync
      RUN_FOR: 280
      SLEEP_FOR_WHEN_OPEN: 10

  service-matcher:
    image: ${env:DOCKER_REGISTRY}/service-matcher:${env:VERSION}
    architecture: x86_64
    name: ${env:PROJECT_ID}-${sls:stage}-service-matcher
    description: ${sls:stage} Service Matcher lambda
    memorySize: 192
    timeout: 10
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/${env:TF_VAR_service_matcher_role_name}
    maximumRetryAttempts: 0
    environment:
      CHANGE_EVENTS_TABLE_NAME: ${env:TF_VAR_change_events_table_name}
      UPDATE_REQUEST_QUEUE_URL: ${env:update_request_queue_url}
      DB_NAME: ${env:DB_NAME}
      DB_PORT: ${env:DB_PORT}
      DB_READ_ONLY_USER_NAME: ${env:DB_READ_ONLY_USER_NAME}
      DB_REPLICA_SECRET_KEY: ${env:DB_REPLICA_SECRET_KEY}
      DB_REPLICA_SECRET_NAME: ${env:DB_REPLICA_SECRET_NAME}
      DB_REPLICA_SERVER: ${env:DB_REPLICA_SERVER}
      DB_SCHEMA: ${env:DB_SCHEMA}
    vpcDiscovery:
      vpcName: '${env:AWS_VPC_NAME}'
      subnets:
        - tagKey: Name
          tagValues:
            - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}a'
            - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}b'
            - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}c'
      securityGroups:
        - tagKey: Name
          tagValues:
            - '${env:TF_VAR_lambda_security_group_name}'

  service-sync:
    image: ${env:DOCKER_REGISTRY}/service-sync:${env:VERSION}
    architecture: x86_64
    name: ${env:PROJECT_ID}-${sls:stage}-service-sync
    description: ${sls:stage} Service Sync lambda
    memorySize: 512
    timeout: 20
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/${env:TF_VAR_service_sync_role_name}
    environment:
      CHANGE_EVENTS_TABLE_NAME: ${env:TF_VAR_change_events_table_name}
      CIRCUIT: DOS_DATABASE
      UPDATE_REQUEST_QUEUE_URL: ${env:update_request_queue_url}
      DB_NAME: ${env:DB_NAME}
      DB_PORT: ${env:DB_PORT}
      DB_READ_ONLY_USER_NAME: ${env:DB_READ_ONLY_USER_NAME}
      DB_REPLICA_SECRET_KEY: ${env:DB_REPLICA_SECRET_KEY}
      DB_REPLICA_SECRET_NAME: ${env:DB_REPLICA_SECRET_NAME}
      DB_REPLICA_SERVER: ${env:DB_REPLICA_SERVER}
      DB_SERVER: ${env:DB_SERVER}
      DB_SCHEMA: ${env:DB_SCHEMA}
      DB_SECRET_KEY: ${env:DB_SECRET_KEY}
      DB_SECRET_NAME: ${env:DB_SECRET_NAME}
      DB_READ_AND_WRITE_USER_NAME: ${env:DB_READ_AND_WRITE_USER_NAME}
    maximumRetryAttempts: 0
    vpcDiscovery:
      vpcName: '${env:AWS_VPC_NAME}'
      subnets:
        - tagKey: Name
          tagValues:
            - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}a'
            - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}b'
            - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}c'
      securityGroups:
        - tagKey: Name
          tagValues:
            - '${env:TF_VAR_lambda_security_group_name}'

  slack-messenger:
    image: ${env:DOCKER_REGISTRY}/slack-messenger:${env:VERSION}
    architecture: x86_64
    name: ${env:PROJECT_ID}-${sls:stage}-slack-messenger
    description: ${sls:stage} Slack Messenger lambda
    memorySize: 128
    timeout: 10
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/${env:TF_VAR_slack_messenger_role_name}
    environment:
      SLACK_ALERT_CHANNEL: ${env:SLACK_ALERT_CHANNEL}
      SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}
    events:
      - sns:
          arn: arn:aws:sns:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:${env:TF_VAR_sns_topic_app_alerts_for_slack}

  dos-db-handler:
    image: ${env:DOCKER_REGISTRY}/dos-db-handler:${env:VERSION}
    architecture: x86_64
    name: ${env:PROJECT_ID}-${sls:stage}-dos-db-handler
    description: ${sls:stage} DoS DB Handler lambda for accessing DoS DB in NonProd
    memorySize: 128
    timeout: 30
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/${env:TF_VAR_dos_db_handler_role_name}
    environment:
      DB_NAME: ${env:DB_NAME}
      DB_PORT: ${env:DB_PORT}
      DB_READ_ONLY_USER_NAME: ${env:DB_READ_ONLY_USER_NAME}
      DB_REPLICA_SECRET_KEY: ${env:DB_REPLICA_SECRET_KEY}
      DB_REPLICA_SECRET_NAME: ${env:DB_REPLICA_SECRET_NAME}
      DB_REPLICA_SERVER: ${env:DB_REPLICA_SERVER}
      DB_SERVER: ${env:DB_SERVER}
      DB_SCHEMA: ${env:DB_SCHEMA}
      DB_SECRET_KEY: ${env:DB_SECRET_KEY}
      DB_SECRET_NAME: ${env:DB_SECRET_NAME}
      DB_READ_AND_WRITE_USER_NAME: ${env:DB_READ_AND_WRITE_USER_NAME}
    maximumRetryAttempts: 0
    vpcDiscovery:
      vpcName: '${env:AWS_VPC_NAME}'
      subnets:
        - tagKey: Name
          tagValues:
            - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}a'
            - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}b'
            - '${env:AWS_VPC_NAME}-private-${env:AWS_REGION}c'
      securityGroups:
        - tagKey: Name
          tagValues:
            - '${env:TF_VAR_lambda_security_group_name}'

resources:
  Conditions:
    CreateNonProdResources:
      !Not [!Equals ["${env:AWS_ACCOUNT_NAME}", prod]]
