# For documentation see here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  pre_build:
    commands:
      - git rev-parse --short HEAD
      - echo
      - echo $PROFILE
      - echo =================================
      - chown -R 999:999 $CODEBUILD_SRC_DIR
      - temp_role=$(aws sts assume-role --role-arn "arn:aws:iam::$AWS_ACCOUNT_ID_NONPROD:role/UECPUPipelineBuildRole" --role-session-name "CodeBuildSessionNonProd")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - make docker-hub-signin
      - make docker-pull NAME=serverless VERSION=latest
      - unset AWS_ACCESS_KEY_ID
      - unset AWS_SECRET_ACCESS_KEY
      - unset AWS_SESSION_TOKEN
      - temp_prod_role=$(aws sts assume-role --role-arn "arn:aws:iam::$AWS_ACCOUNT_ID_PROD:role/UECPUPipelineBuildRole" --role-session-name "CodeBuildSessionProd")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_prod_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_prod_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_prod_role | jq -r .Credentials.SessionToken)
  build:
    commands:
      - echo "[Deploying]"
      - make terraform-apply-auto-approve STACKS=appconfig PROFILE=$PROFILE ENVIRONMENT=$ENVIRONMENT
